version: "3.9"

services:
  cf-bypass:
    image: harlekesp/cf-football-bypass:latest
    container_name: cf-football-bypass
    restart: always
    environment:
      DOMAINS: '[{"name":"casa-carreras.es","record":"@","type":"A"}]'
      INTERVAL_SECONDS: 300
    secrets:
      - cf_api_token
      - cf_zone_id
    volumes:
      - cflogs:/app/logs
    networks:
      - private_network

secrets:
  cf_api_token:
    file: ./cf_api_token.txt
  cf_zone_id:
    file: ./cf_zone_id.txt

volumes:
  cflogs:

networks:
  private_network: